name: "E2E Tests"
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"


      - name: Run E2E tests
        run: |
          nix develop --command bash -c 'cd e2e && npm install && . ./run_invisible.sh @dev'
